env:
  MIRROR_URL:
    "git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-romain.schneider.git"

on: [push, pull_request]
jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: "find * -type f \\( -name '#*#' -o -name '*~' -o -name '*pain_au_chocolat*' -o -name '*.o' -o -name '*.a' -o -name '*.so' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov' -o -path '*tmp/*' \\) -exec echo '::error file={},line=1,endLine=0,title=Unwanted file detected::{}' \\; -exec false {} +"
  check_program_compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make
        timeout-minutes: 2
      - run: make clean
  run_tests:
    runs-on: ubuntu-latest
    container: actions/runepitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make tests_run
        timeout-minutes: 2
  push_to_mirror:
    needs: cleanup
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}